### ISSUE TITLE
I don't see Driftmode in drive menu

### ISSUE THREAD

**Issue by KamilLenica** [Brewsk11/ac-drift-mode#1]
Hi,

I am runnig manuallt installed DrifMode 2.5.0
Content manager 0.8.2561.39678 (x86)
CSP 0.1.79

Settings are as such:
<img width="749" alt="image" src="https://github.com/Brewsk11/ac-drift-mode/assets/2961046/cc281549-7563-49e5-ab0c-c9bbc0e61e31">

But still cannot get to start DriftMode
<img width="756" alt="image" src="https://github.com/Brewsk11/ac-drift-mode/assets/2961046/22052064-1812-4a19-9427-8c929e903c7d">

**Comment by Brewsk11** [comment]
Hi, for CSP 0.1.79 only the CSP settings are required to be set to DriftMode.
Run on "Practice" mode with the settings you currently have and see if everything works.

**Comment by KamilLenica** [comment]
It looks like script started, but still i do not have possibility to configure car and track

<img width="414" alt="image" src="https://github.com/Brewsk11/ac-drift-mode/assets/2961046/ff2ac481-68ce-4dbe-9b5d-2e300051e2f9">

**Comment by Brewsk11** [comment]
Please change this line https://github.com/Brewsk11/ac-drift-mode/blob/master/apps/drift-mode/drift-mode.lua#L324 to:

```
  ui.image(Resources.EmblemFlat, vec2(ui.availableSpaceX(), logo_height), true)
```

I'll address this in 2.5.1.

**Comment by KamilLenica** [comment]
OK, now Control Panel loads, but Drift status doesn't And i cannot use helper camera in car Editor nor edit zones on track.

This is first time i am trying to use this mod, what's the combination of track / car, that this should work?

**Comment by Brewsk11** [comment]
As for combintation - any, however some tracks have broken physics after patching the track. Kunos' "Drift" track is where I'm doing most of my testing on.

I'll spin up 0.1.79 + 2.5.0 and see if there are any problems.

**Comment by Brewsk11** [comment]
Please have a look at this version: [ac-drift-mode-2.5.0-2-g72cc1a4.zip](https://github.com/Brewsk11/ac-drift-mode/files/12703100/ac-drift-mode-2.5.0-2-g72cc1a4.zip)
and see there are any problems left.

**Comment by KamilLenica** [comment]
Yes, this version works

**Comment by Brewsk11** [comment]
Great, thanks for the bug report!

**Comment by KamilLenica** [comment]
Not a problem!
